service: earnings

gateway: http://127.0.0.1:9001

base_url: https://submit.shutterstock.com/earnings/daily?page={}&date={}&language=en&category={}&sort=desc&sorted_by=count&per_page=20

map_url: https://submit.shutterstock.com/api/user/downloads/map

categories:
  25_a_day: subscription
  on_demand: onDemand
  enhanced: enhanced
  single_image_and_other: single&other

#hosts:
#  api-server: api
#  slack-service: slack
#  earnings-sheduler: earnings
#
#ports:
#  api-server: 8001
#  slack-service: 8005
#  earnings-sheduler: 8003